name: Run Private Github Action

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
  awesome:
    name: Awesome Action
    runs-on: ubuntu-latest
    steps:
      # checkout this repo
      - name: Checkout Repo
        uses: actions/checkout@v2
      # checkout the private repo containing the action to run
      - name: Checkout GitHub Action Repo
        uses: actions/checkout@v2
        with:
          repository: ${{ REPO }}
          ref: v0.1.2
          token: ${{ secrets.GIT_HUB_TOKEN }}   # stored in GitHub secrets
          path: .github/actions/private-action
      - name: Run My Action
        uses: ./.github/actions/private-action
